CdDiskStoreAspNetCore/Controllers/DiscsController.cs
using CdDiskStoreAspNetCore.Data.Models;
using CdDiskStoreAspNetCore.Data.Repository;
using CdDiskStoreAspNetCore.Models;
using CdDiskStoreAspNetCore.Models.Enums;
using CdDiskStoreAspNetCore.Utilities.Attributes;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Text.RegularExpressions;

namespace CdDiskStoreAspNetCore.Controllers
{
    [Authorize]
    public class DiscsController : Controller
    {
        private readonly IDiscRepository _discRepository;

        public DiscsController(IDiscRepository discRepository)
        {
            this._discRepository = discRepository;
        }

        public async Task<IActionResult> Index(string? filter, MySortOrder sortOrder, string? filterFieldName, string? sortField = "Id", int skip = 0)
        {
            var model = new IndexViewModel<Disc>
            {
                Filter = filter,
                FilterFieldName = filterFieldName ?? IndexViewModel<Disc>.FilterableFieldNames[0],
                SortFieldName = sortField,
                SortOrder = sortOrder,
                Skip = skip,
                CountItems = await this._discRepository.GetProcessedDataCountAsync(filter, filterFieldName)
            };

            model.Items = await this._discRepository.GetProcessedDataAsync(model.Filter, model.FilterFieldName, model.SortOrder, model.SortFieldName, model.Skip, model.PageSize);

            return View(model);
        }

        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null || this._discRepository == null)
            {
                return NotFound();
            }

            try
            {
                var model = new DiscsDetailsViewModel
                {
                    Disc = await this._discRepository.GetByIdAsync(id),
                    Type = await this._discRepository.GetTypeAsync(id)
                };

                if (model.Type.Contains("Film"))
                {
                    model.Films = await this._discRepository.GetFilmsAsync(id);
                }

                if(model.Type.Contains("Music"))
                {
                    model.Musics = await this._discRepository.GetMusicsAsync(id);
                }
                return View(model);
            }
            catch (NullReferenceException ex)
            {
                return NotFound(ex.Message);
            }
        }

        [Authorize(Roles = "Administrator, Manager")]
        public async Task<IActionResult> Create(Guid? id)
        {
            if (id == null)
            {
                ViewData["Action"] = "Create";
                return View();
            }

            ViewData["Action"] = "Edit";
            try
            {
                var disc = await this._discRepository.GetByIdAsync(id);
                return View(disc);
            }
            catch (NullReferenceException ex)
            {
                return NotFound(ex.Message);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator, Manager")]
        public async Task<IActionResult> Create(Guid? id, [Bind("Id,Name,Price")] Disc disc)
        {
            if (!ModelState.IsValid && !ValidateDisc(disc))
            {
                return View(disc);
            }

            if (id == null)
            {
                disc.Id = Guid.NewGuid();

                await this._discRepository.AddAsync(disc);

                return RedirectToAction(nameof(Index));
            }

            if (id != disc.Id)
            {
                return NotFound();
            }

            try
            {
                await this._discRepository.UpdateAsync(disc);
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!await this._discRepository.ExistsAsync(disc.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }

        private bool ValidateDisc(Disc disc)
        {
            if (!Regex.IsMatch(disc.Price.ToString(), PriceValidation.PricePattern))
            {
                ModelState.AddModelError("Price", "Incorrect price set. Price must be set in range from 0 to 0.00 to 99999999.99");
                return false;
            }

            return true;
        }

        [Authorize(Roles = "Administrator, Manager")]
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null || this._discRepository == null)
            {
                return NotFound();
            }

            try
            {
                var disc = await this._discRepository.GetByIdAsync(id);
                return Ok();
            }
            catch (NullReferenceException ex)
            {
                return NotFound(ex.Message);
            }
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator, Manager")]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            if (this._discRepository == null)
            {
                return Problem("Repository class implementing 'IClientRepository' is null.");
            }

            var disc = await this._discRepository.GetByIdAsync(id);

            if (disc != null)
            {
                await this._discRepository.DeleteAsync(disc.Id);
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

CdDiskStoreAspNetCore/Controllers/FilmsController.cs
using CdDiskStoreAspNetCore.Data.Models;
using CdDiskStoreAspNetCore.Data.Repository;
using CdDiskStoreAspNetCore.Models;
using CdDiskStoreAspNetCore.Models.Enums;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CdDiskStoreAspNetCore.Controllers
{
    [Authorize]
    public class FilmsController : Controller
    {
        private readonly IFilmRepository _filmRepository;

        public FilmsController(IFilmRepository filmRepository)
        {
            this._filmRepository = filmRepository;
        }

        public async Task<IActionResult> Index(string? filter, MySortOrder sortOrder, string? filterFieldName, string? sortField = "Id", int skip = 0)
        {
            var model = new IndexViewModel<Film>
            {
                Filter = filter,
                FilterFieldName = filterFieldName ?? IndexViewModel<Film>.FilterableFieldNames[0],
                SortFieldName = sortField,
                SortOrder = sortOrder,
                Skip = skip,
                CountItems = await this._filmRepository.GetProcessedDataCountAsync(filter, filterFieldName)
            };

            model.Items = await this._filmRepository.GetProcessedDataAsync(model.Filter, model.FilterFieldName, model.SortOrder, model.SortFieldName, model.Skip, model.PageSize);

            return View(model);
        }

        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null || this._filmRepository == null)
            {
                return NotFound();
            }

            try
            {
                var model = new FilmsDetailsViewModel
                {
                    Film = await this._filmRepository.GetByIdAsync(id),
                    Discs = await this._filmRepository.GetDiscsAsync(id)
                };
                return View(model);
            }
            catch (NullReferenceException ex)
            {
                return NotFound(ex.Message);
            }

        }

        [Authorize(Roles = "Administrator, Manager")]
        public async Task<IActionResult> Create(Guid? id)
        {
            if (id == null)
            {
                ViewData["Action"] = "Create";
                return View();
            }

            ViewData["Action"] = "Edit";
            try
            {
                var film = await this._filmRepository.GetByIdAsync(id);
                return View(film);
            }
            catch (NullReferenceException ex)
            {
                return NotFound(ex.Message);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator, Manager")]
        public async Task<IActionResult> Create(Guid? id, [Bind("Id,Name,Genre,Producer,MainRole,AgeLimit")] Film film)
        {
            if (!ModelState.IsValid && !ValidateFilm(film))
            {
                return View(film);
            }

            if (id == null)
            {
                film.Id = Guid.NewGuid();

                await this._filmRepository.AddAsync(film);

                return RedirectToAction(nameof(Index));
            }

            if (id != film.Id)
            {
                return NotFound();
            }

            try
            {
                await this._filmRepository.UpdateAsync(film);
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!await this._filmRepository.ExistsAsync(film.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }

        private bool ValidateFilm(Film film)
        {
            if (film.AgeLimit < 0 || film.AgeLimit > 18)
            {
                ModelState.AddModelError("Age limit", "Incorrect age limit set. Age limit must be set in range from 0 to 18");
                return false;
            }

            return true;
        }

        [Authorize(Roles = "Administrator, Manager")]
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null || this._filmRepository == null)
            {
                return NotFound();
            }

            try
            {
                var film = await this._filmRepository.GetByIdAsync(id);
                return Ok();
            }
            catch (NullReferenceException ex)
            {
                return NotFound(ex.Message);
            }
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator, Manager")]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            if (this._filmRepository == null)
            {
                return Problem("Repository class implementing 'IClientRepository' is null.");
            }

            var film = await this._filmRepository.GetByIdAsync(id);

            if (film != null)
            {
                await this._filmRepository.DeleteAsync(film.Id);
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

CdDiskStoreAspNetCore/Controllers/MusicsController.cs
using CdDiskStoreAspNetCore.Data.Models;
using CdDiskStoreAspNetCore.Data.Repository;
using CdDiskStoreAspNetCore.Models;
using CdDiskStoreAspNetCore.Models.Enums;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CdDiskStoreAspNetCore.Controllers
{
    [Authorize]
    public class MusicsController : Controller
    {
        private readonly IMusicRepository _musicRepository;

        public MusicsController(IMusicRepository musicRepository)
        {
            this._musicRepository = musicRepository;
        }

        public async Task<IActionResult> Index(string? filter, MySortOrder sortOrder, string? filterFieldName, string? sortField = "Id", int skip = 0)
        {
            var model = new IndexViewModel<Music>
            {
                Filter = filter,
                FilterFieldName = filterFieldName ?? IndexViewModel<Music>.FilterableFieldNames[0],
                SortFieldName = sortField,
                SortOrder = sortOrder,
                Skip = skip,
                CountItems = await this._musicRepository.GetProcessedDataCountAsync(filter, filterFieldName)
            };

            model.Items = await this._musicRepository.GetProcessedDataAsync(model.Filter, model.FilterFieldName, model.SortOrder, model.SortFieldName, model.Skip, model.PageSize);

            return View(model);
        }

        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null || this._musicRepository == null)
            {
                return NotFound();
            }

            try
            {
                var model = new MusicsDetailsViewModel
                {
                    Music = await this._musicRepository.GetByIdAsync(id),
                    Discs = await this._musicRepository.GetDiscsAsync(id)
                };
                return View(model);
            }
            catch (NullReferenceException ex)
            {
                return NotFound(ex.Message);
            }

        }

        [Authorize(Roles = "Administrator, Manager")]
        public async Task<IActionResult> Create(Guid? id)
        {
            if (id == null)
            {
                ViewData["Action"] = "Create";
                return View();
            }

            ViewData["Action"] = "Edit";
            try
            {
                var film = await this._musicRepository.GetByIdAsync(id);
                return View(film);
            }
            catch (NullReferenceException ex)
            {
                return NotFound(ex.Message);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator, Manager")]
        public async Task<IActionResult> Create(Guid? id, [Bind("Id,Name,Genre,Artist,Language")] Music music)
        {
            if (!ModelState.IsValid)
            {
                return View(music);
            }

            if (id == null)
            {
                music.Id = Guid.NewGuid();

                await this._musicRepository.AddAsync(music);

                return RedirectToAction(nameof(Index));
            }

            if (id != music.Id)
            {
                return NotFound();
            }

            try
            {
                await this._musicRepository.UpdateAsync(music);
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!await this._musicRepository.ExistsAsync(music.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Administrator, Manager")]
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null || this._musicRepository == null)
            {
                return NotFound();
            }

            try
            {
                var music = await this._musicRepository.GetByIdAsync(id);
                return Ok();
            }
            catch (NullReferenceException ex)
            {
                return NotFound(ex.Message);
            }
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator, Manager")]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            if (this._musicRepository == null)
            {
                return Problem("Repository class implementing 'IClientRepository' is null.");
            }

            var music = await this._musicRepository.GetByIdAsync(id);

            if (music != null)
            {
                await this._musicRepository.DeleteAsync(music.Id);
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

CdDiskStoreAspNetCore/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManger
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CdDiskStoreAspNetCore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CdDiskStoreAspNetCore.styles.css" asp-append-version="true" />
    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
    <link rel="icon" href="~/lib/disc.ico" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CD Discs Store</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (SignInManger.IsSignedIn(User) && (User.IsInRole("Administrator") || User.IsInRole("Manager") || User.IsInRole("User")))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Clients" asp-action="Index">Clients</a>
                            </li>
                        }

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Discs" asp-action="Index">Discs</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Films" asp-action="Index">Films</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Musics" asp-action="Index">Music</a>
                        </li>

                        @if (SignInManger.IsSignedIn(User))
                        {
                            var user = await UserManager.GetUserAsync(User);
                            if (user != null && await UserManager.IsInRoleAsync(user, "Administrator"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="AdminPanel" asp-action="Index">Admin Panel</a>
                                </li>
                            }
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CD Discs Store - <a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CdDiskStoreAspNetCore/Views/Shared/_Pagination.cshtml
@model object
@using CdDiskStoreAspNetCore.Models.Interfaces.Data;

@{
    if (Model is not IDataProcessable processable)
    {
        <p>
            IDataProcessable interface is not implemented
        </p>
    }
    else
    {
        int pages = processable.CountItems / processable.PageSize + (processable.CountItems % processable.PageSize > 0 ? 1 : 0);
        if (pages > 1)
        {
            int currentPage = processable.Skip == 0 ? 1 : processable.Skip / processable.PageSize + 1;
            string previousState = processable.Skip == 0 ? "disabled" : "";

            <nav aria-label="...">
                <ul class="pagination justify-content-center">
                    @{
                        <li class="page-item @(currentPage == 1 ? "disabled" : "")">
                            <a class="page-link" asp-page=""
                               asp-route-skip="0"
                               asp-route-sortField="@processable.SortFieldName"
                               asp-route-filterFieldName="@processable.FilterFieldName"
                               asp-route-filter="@processable.Filter">First</a>
                        </li>

                        <li class="page-item @(currentPage == 1 ? "disabled" : "")">
                            <a class="page-link" asp-page=""
                               asp-route-skip="@((currentPage-2)*processable.PageSize)"
                               asp-route-sortField="@processable.SortFieldName"
                               asp-route-filterFieldName="@processable.FilterFieldName"
                               asp-route-filter="@processable.Filter">
                                <i class="fa-solid fa-chevron-left"></i>
                            </a>
                        </li>

                        int start = Math.Max(0, Math.Min(currentPage - 5, pages - 9));
                        int buttons = Math.Min(pages, 9);

                        for (int i = 1; i <= buttons; i++)
                        {
                            int pageNumber = i + start;
                            if (currentPage == pageNumber)
                            {
                                <li class="page-item active" aria-current="page">
                                    <span class="page-link">@pageNumber</span>
                                </li>
                            }
                            else
                            {
                                <li class="page-item">
                                    <a class="page-link" asp-page=""
                                       asp-route-skip="@((pageNumber-1)*processable.PageSize)"
                                       asp-route-sortField="@processable.SortFieldName"
                                       asp-route-filterFieldName="@processable.FilterFieldName"
                                       asp-route-filter="@processable.Filter">@pageNumber</a>
                                </li>
                            }
                        }

                        <li class="page-item @(currentPage == pages ? "disabled" : "")">
                            <a class="page-link" asp-page=""
                               asp-route-skip="@((currentPage)*processable.PageSize)"
                               asp-route-sortField="@processable.SortFieldName"
                               asp-route-filterFieldName="@processable.FilterFieldName"
                               asp-route-filter="@processable.Filter">
                                <i class="fa-solid fa-chevron-right"></i>
                            </a>
                        </li>

                        <li class="page-item @(currentPage == pages ? "disabled" : "")">
                            <a class="page-link" asp-page=""
                               asp-route-skip="@((pages-1)*processable.PageSize)"
                               asp-route-sortField="@processable.SortFieldName"
                               asp-route-filterFieldName="@processable.FilterFieldName"
                               asp-route-filter="@processable.Filter">Last</a>
                        </li>

                    }
                </ul>
            </nav>
        }
    }
}

CdDiskStoreAspNetCore/Views/Shared/_SortField.cshtml
@using CdDiskStoreAspNetCore.Models.Enums
@using CdDiskStoreAspNetCore.Models.Interfaces;
@using CdDiskStoreAspNetCore.Models.Interfaces.Data;
@model CdDiskStoreAspNetCore.Models.SortModel

@{
    if (Model.ViewModel is not IDataProcessable processable)
    {
        <p>
            IDataProcessable interface is not implemented
        </p>
    }
    else
    {
        string arrow = "";

        if (processable.SortFieldName == Model.FieldName)
        {
            processable.SortOrder = (processable.SortOrder == MySortOrder.Ascending)
                ? MySortOrder.Descending
                : MySortOrder.Ascending;

            arrow = (processable.SortOrder == MySortOrder.Ascending)
            ? "fa-sort-up"
            : "fa-sort-down";
        }
        
        <a asp-action="Index"
           asp-route-sortField="@Model.FieldName"
           asp-route-sortOrder="@processable.SortOrder"
           asp-route-filterFieldName="@processable.FilterFieldName"
           asp-route-filter="@processable.Filter"
           asp-route-skip="@processable.Skip">
            @Model.FieldName <i class="fas @arrow"></i>
        </a>
    }
}