CdDiskStoreAspNetCore/Controllers/ClientsController.cs
using CdDiskStoreAspNetCore.Data.Models;
using CdDiskStoreAspNetCore.Data.Repository;
using CdDiskStoreAspNetCore.Models;
using CdDiskStoreAspNetCore.Models.Enums;
using CdDiskStoreAspNetCore.Utilities.Attributes;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Text.RegularExpressions;

namespace CdDiskStoreAspNetCore.Controllers
{
    [Authorize(Roles = "Administrator, Manager, User")]
    public class ClientsController : Controller
    {
        private readonly IClientRepository _clientRepository;

        public ClientsController(IClientRepository clientRepository)
        {
            this._clientRepository = clientRepository;
        }

        public async Task<IActionResult> Index(string? filter, MySortOrder sortOrder, string? filterFieldName, string? sortField = "Id", int skip = 0)
        {
            var model = new IndexViewModel<Client>
            {
                Filter = filter,
                FilterFieldName = filterFieldName ?? IndexViewModel<Client>.FilterableFieldNames[0],
                SortFieldName = sortField,
                SortOrder = sortOrder,
                Skip = skip,
                CountItems = await this._clientRepository.GetProcessedDataCountAsync(filter, filterFieldName)
            };

            model.Items = await this._clientRepository.GetProcessedDataAsync(model.Filter, model.FilterFieldName, model.SortOrder, model.SortFieldName, model.Skip, model.PageSize);

            return View(model);
        }

        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null || this._clientRepository == null)
            {
                return NotFound();
            }

            try
            {
                var model = new ClientDetailsViewModel()
                {
                    Client = await this._clientRepository.GetByIdAsync(id),
                    PersonalDiscount = await this._clientRepository.GetPersonalDiscountAsync(id),
                    RentProfit = await this._clientRepository.GetTotalRentProfitAsync(id),
                    PurchaseProfit = await this._clientRepository.GetTotalPurchaseProfitAsync(id),
                    TotalProfit = await this._clientRepository.GetTotalProfitAsync(id),
                    ContactPhones = await this._clientRepository.GetPhonesAsync(id),
                    ContactMails = await this._clientRepository.GetMailsAsync(id)
                };

                return View(model);
            }
            catch (NullReferenceException ex)
            {
                return NotFound(ex.Message);
            }
        }

        [Authorize(Roles = "Administrator, Manager")]
        public async Task<IActionResult> Create(Guid? id)
        {
            if (id == null)
            {
                ViewData["Action"] = "Create";
                return View();
            }

            ViewData["Action"] = "Edit";
            try
            {
                var client = await this._clientRepository.GetByIdAsync(id);
                return View(client);
            }
            catch (NullReferenceException ex)
            {
                return NotFound(ex.Message);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator, Manager")]
        public async Task<IActionResult> Create(Guid? id, [Bind("Id,FirstName,LastName,Address,City,ContactPhone,ContactMail,BirthDay,MarriedStatus,Sex,HasChild")] Client client)
        {
            if (!ModelState.IsValid && !ValidateContactDetails(client))
            {
                return View(client);
            }

            if (id == null)
            {
                client.Id = Guid.NewGuid();

                await this._clientRepository.AddAsync(client);

                return RedirectToAction(nameof(Index));
            }

            if (id != client.Id)
            {
                return NotFound();
            }

            try
            {
                await this._clientRepository.UpdateAsync(client);
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!await this._clientRepository.ExistsAsync(client.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }

        private bool ValidateContactDetails(Client client)
        {
            if (!Regex.IsMatch(client.ContactPhone, PhoneValidation.PhonePattern))
            {
                ModelState.AddModelError("Contact Phone", "Contact phone does not match the pattern: 'xx-xxx-xx-xx'");
                return false;
            }

            if (!Regex.IsMatch(client.ContactMail, EmailAddressValidation.EmailPattern))
            {
                ModelState.AddModelError("Contact Mail", "Contact mail does not match the pattern: 'user@example.com'");
                return false;
            }

            return true;
        }

        [Authorize(Roles = "Administrator, Manager")]
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null || this._clientRepository == null)
            {
                return NotFound();
            }

            try
            {
                var client = await this._clientRepository.GetByIdAsync(id);
                return Ok();
            }
            catch (NullReferenceException ex)
            {
                return NotFound(ex.Message);
            }
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator, Manager")]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            if (this._clientRepository == null)
            {
                return Problem("Repository class implementing 'IClientRepository' is null.");
            }

            var client = await this._clientRepository.GetByIdAsync(id);

            if (client != null)
            {
                await this._clientRepository.DeleteAsync(client.Id);
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

CdDiskStoreAspNetCore/Views/Clients/Create.cshtml
@inject SignInManager<IdentityUser> SignInManger
@model CdDiskStoreAspNetCore.Data.Models.Client

@{
    string action = ViewData["Action"] as string;
}

@if (!SignInManger.IsSignedIn(User) && (!User.IsInRole("Administrator") || !User.IsInRole("Manager")))
{
    <h1 style="color: red;">ACCESS DENIED</h1>
}
else
{
    <div class="container mt-3">
        <h1>@action</h1>

        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Client</h4>
                <hr />
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="FirstName" class="control-label"></label>
                        <input asp-for="FirstName" class="form-control" />
                        <span asp-validation-for="FirstName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="LastName" class="control-label"></label>
                        <input asp-for="LastName" class="form-control" />
                        <span asp-validation-for="LastName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Address" class="control-label"></label>
                        <input asp-for="Address" class="form-control" />
                        <span asp-validation-for="Address" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="City" class="control-label"></label>
                        <input asp-for="City" class="form-control" />
                        <span asp-validation-for="City" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ContactPhone" class="control-label"></label>
                        <input type="tel" placeholder="0501234567" asp-for="ContactPhone" class="form-control" />
                        <small id="phoneHelp" class="form-text text-muted">Будь ласка, введіть свій номер телефону в українському форматі (0501234567).</small>
                        <span asp-validation-for="ContactPhone" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ContactMail" class="control-label"></label>
                        <input placeholder="user@example.com" asp-for="ContactMail" class="form-control" />
                        <span asp-validation-for="ContactMail" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="BirthDay" class="control-label"></label>
                        <input asp-for="BirthDay" class="form-control" />
                        <span asp-validation-for="BirthDay" class="text-danger"></span>
                    </div>
                    <div class="form-group form-check">
                        <label class="form-check-label">
                            <input class="form-check-input" asp-for="MarriedStatus" /> @Html.DisplayNameFor(model => model.MarriedStatus)
                        </label>
                    </div>
                    <div class="form-group form-check">
                        <label class="form-check-label">
                            <input class="form-check-input" asp-for="Sex" /> @Html.DisplayNameFor(model => model.Sex)
                        </label>
                    </div>
                    <div class="form-group form-check">
                        <label class="form-check-label">
                            <input class="form-check-input" asp-for="HasChild" /> @Html.DisplayNameFor(model => model.HasChild)
                        </label>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="@action" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>

        <div class="mt-3">
            <a asp-action="Index" class="btn btn-secondary">Back to List</a>
        </div>
    </div>
}

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

CdDiskStoreAspNetCore/Views/Clients/Details.cshtml
@inject SignInManager<IdentityUser> SignInManger
@model CdDiskStoreAspNetCore.Models.ClientDetailsViewModel

@if (TempData["SuccessMessage"] != null)
{
    <div class="alert alert-success">
        @TempData["SuccessMessage"]
    </div>
}

<div class="container mt-3">
    <h1 class="mb-4">Details</h1>

    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Client</h4>
            <hr />

            <table class="table table-bordered table-striped">
                <tr>
                    <th class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Client.FirstName)
                    </th>
                    <td class="col-sm-10">
                        @Html.DisplayFor(model => model.Client.FirstName)
                    </td>
                </tr>
                <tr>
                    <th class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Client.LastName)
                    </th>
                    <td class="col-sm-10">
                        @Html.DisplayFor(model => model.Client.LastName)
                    </td>
                </tr>
                <tr>
                    <th class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Client.Address)
                    </th>
                    <td class="col-sm-10">
                        @Html.DisplayFor(model => model.Client.Address)
                    </td>
                </tr>
                <tr>
                    <th class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Client.City)
                    </th>
                    <td class="col-sm-10">
                        @Html.DisplayFor(model => model.Client.City)
                    </td>
                </tr>
                <tr>
                    <th class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Client.ContactPhone)
                    </th>
                    <td class="col-sm-10">
                        @Html.DisplayFor(model => model.Client.ContactPhone)
                    </td>
                </tr>
                <tr>
                    <th class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Client.ContactMail)
                    </th>
                    <td class="col-sm-10">
                        @Html.DisplayFor(model => model.Client.ContactMail)
                    </td>
                </tr>
                <tr>
                    <th class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Client.BirthDay)
                    </th>
                    <td class="col-sm-10">
                        @Html.DisplayFor(model => model.Client.BirthDay)
                    </td>
                </tr>
                <tr>
                    <th class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Client.MarriedStatus)
                    </th>
                    <td class="col-sm-10">
                        @Html.DisplayFor(model => model.Client.MarriedStatus)
                    </td>
                </tr>
                <tr>
                    <th class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Client.Sex)
                    </th>
                    <td class="col-sm-10">
                        @Html.DisplayFor(model => model.Client.Sex)
                    </td>
                </tr>
                <tr>
                    <th class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Client.HasChild)
                    </th>
                    <td class="col-sm-10">
                        @Html.DisplayFor(model => model.Client.HasChild)
                    </td>
                </tr>
                <tr>
                    <th class="col-sm-2">
                        @Html.DisplayNameFor(model => model.PersonalDiscount)
                    </th>
                    <td class="col-sm-10">
                        @Html.DisplayFor(model => model.PersonalDiscount) %
                    </td>
                </tr>
                <tr>
                    <th class="col-sm-2">
                        @Html.DisplayNameFor(model => model.TotalProfit)
                    </th>
                    <td class="col-sm-10">
                        @Html.DisplayFor(model => model.TotalProfit)
                    </td>
                </tr>
                <tr>
                    <th class="col-sm-2">
                        @Html.DisplayNameFor(model => model.RentProfit)
                    </th>
                    <td class="col-sm-10">
                        @Html.DisplayFor(model => model.RentProfit)
                    </td>
                </tr>
                <tr>
                    <th class="col-sm-2">
                        @Html.DisplayNameFor(model => model.PurchaseProfit)
                    </th>
                    <td class="col-sm-10">
                        @Html.DisplayFor(model => model.PurchaseProfit)
                    </td>
                </tr>
            </table>
        </div>
    </div>

    <br />

    @if (Model.ContactPhones != null && Model.ContactPhones.Any())
    {
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Contact Phones</h4>
                <hr />

                <table class="table table-responsive">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(modelItem => Model.ContactPhones)
                            </th>
                            <th></th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach (var item in Model.ContactPhones)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item)
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    }

    <br />

    @if (Model.ContactMails != null && Model.ContactMails.Any())
    {
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Contact Mails</h4>
                <hr />

                <table class="table table-responsive">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(modelItem => Model.ContactMails)
                            </th>
                            <th></th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach (var item in Model.ContactMails)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item)
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    }

    <div class="mt-3">
        @if (SignInManger.IsSignedIn(User) && User.IsInRole("Administrator"))
        {
            <div>
                <button class="btn btn-primary mb-2 w-100" data-bs-toggle="modal" data-bs-target="#changeDiscountModal">
                    Change Discount Level For Client
                </button>
            </div>

            <div class="modal fade" id="changeDiscountModal" tabindex="-1" aria-labelledby="changeDiscountModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="changeDiscountModalLabel">Change Discount Level For Client</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            <form method="post" asp-controller="ChangeDiscountLevel" asp-action="Execute" asp-route-idClient="@Model.Client.Id" asp-route-increase="@Model.Increase">
                                <div class="mb-3">
                                    <label asp-for="Increase" class="form-label">Increase (otherwise decrease):</label>
                                    <input asp-for="Increase" type="checkbox" class="form-check-input" />
                                    <span asp-validation-for="Increase" class="text-danger"></span>
                                </div>

                                <button type="submit" class="btn btn-primary">Execute</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        }

        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
            @if (SignInManger.IsSignedIn(User) && (User.IsInRole("Administrator") || User.IsInRole("Manager")))
            {
                <a asp-action="Create" asp-route-id="@Model?.Client.Id" class="btn btn-primary me-md-2">Edit</a>
            }
            <a asp-action="Index" class="btn btn-secondary">Back to List</a>
        </div>
    </div>
</div>

CdDiskStoreAspNetCore/Views/Clients/Index.cshtml
@using CdDiskStoreAspNetCore.Data.Models
@inject SignInManager<IdentityUser> SignInManger
@model IndexViewModel<Client>

@{
    ViewData["Title"] = "Index";
}

<h1>Сlients</h1>

<div class="container">
    @if (SignInManger.IsSignedIn(User) && (User.IsInRole("Administrator") || User.IsInRole("Manager")))
    {
        <div class="row mb-3">
            <div class="col-md-3">
                <h3>Create new client</h3>
            </div>
            <div class="col-md-1">
                <a asp-action="Create">
                    <i class="icon-button add-button fas fa-plus"></i>
                </a>
            </div>
        </div>
    }

    <form asp-controller="Clients" asp-action="Index" method="post">
        <div class="row mb-3">
            <div class="col-md-4">
                <div class="form-group">
                    <label asp-for="FilterFieldName">Filter by:</label>
                    @Html.DropDownList("FilterFieldName", new SelectList(IndexViewModel<Client>.FilterableFieldNames, Model.FilterFieldName), new { @class = "form-control" })
                </div>
            </div>

            <div class="col-md-5">
                <div class="form-group">
                    <label for="filter">Filter:</label>
                    <input type="text" id="filter" name="filter" value="@Model.Filter" class="form-control" />
                </div>
            </div>

            <div class="col-md-3 d-grid">
                <input type="submit" value="Filter" class="btn btn-primary" title="Filter" />
            </div>
        </div>
    </form>

    <div class="row" style="width: 80vw;">
        @if (Model.Items != null && Model.Items.Any())
        {
            <table class="table table-responsive">
                <thead>
                    <tr>
                        @foreach (string field in IndexViewModel<Client>.AllFieldNames)
                        {
                            if (field != "Id")
                            {
                                <th>
                                    @{
                                        await Html.RenderPartialAsync("_SortField", new SortModel { ViewModel = Model, FieldName = field });
                                    }
                                </th>
                            }
                        }
                        <th></th>
                    </tr>
                </thead>

                <tbody>
                    @foreach (var item in Model.Items)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.FirstName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.LastName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Address)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.City)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.ContactPhone)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.ContactMail)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.BirthDay)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.MarriedStatus)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Sex)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.HasChild)
                            </td>

                            <td>
                                @if (SignInManger.IsSignedIn(User) && (User.IsInRole("Administrator") || User.IsInRole("Manager")))
                                {
                                    <a asp-action="Create" asp-route-id="@item.Id">
                                        <i class="icon-button edit-button fas fa-edit"></i>
                                    </a>
                                }

                                <a asp-action="Details" asp-route-id="@item.Id">
                                    <i class="icon-button details-button fas fa-eye"></i>
                                </a>

                                @if (SignInManger.IsSignedIn(User) && (User.IsInRole("Administrator") || User.IsInRole("Manager")))
                                {
                                    <button type="button" class="icon-button delete-button fas fa-trash-alt" data-bs-toggle="modal" data-bs-target="#exampleModal@(item.Id)"></button>

                                    <div class="modal fade" id="exampleModal@(item.Id)" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="exampleModalLabel">Client to delete</h5>
                                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                                </div>
                                                <div class="modal-body">
                                                    @{
                                                        string clientFullName = item.FirstName + " " + item.LastName;
                                                    }
                                                    @Html.DisplayFor(modelItem => clientFullName)
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                                    <form method="post" asp-action="Delete" asp-route-id="@item.Id">
                                                        <input type="hidden" asp-for="@item.Id" />
                                                        <input type="submit" value="Delete" class="btn btn-danger" />
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                }
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <h1>No clients in database</h1>
        }

        @{
            await Html.RenderPartialAsync("_Pagination", Model);
        }
    </div>
</div>