CdDiskStoreAspNetCore/Controllers/AdminPanelController.cs
using CdDiskStoreAspNetCore.Data.Repository;
using CdDiskStoreAspNetCore.Models;
using CdDiskStoreAspNetCore.Models.Enums;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace CdDiskStoreAspNetCore.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class AdminPanelController : Controller
    {
        private readonly IIdentityUserRepository _userRepository;

        public AdminPanelController(IIdentityUserRepository userRepository)
        {
            this._userRepository = userRepository;
        }

        public async Task<IActionResult> Index(string? filter, MySortOrder sortOrder, string? filterFieldName, string? sortField = "Id", int skip = 0)
        {
            var model = new IndexViewModel<IdentityUser>
            {
                Filter = filter,
                FilterFieldName = filterFieldName ?? IndexViewModel<IdentityUser>.FilterableFieldNames[0],
                SortFieldName = sortField,
                SortOrder = sortOrder,
                Skip = skip,
                CountItems = await this._userRepository.GetProcessedDataCountAsync(filter, filterFieldName)
            };

            model.Items = await this._userRepository.GetProcessedDataAsync(model.Filter, model.FilterFieldName, model.SortOrder, model.SortFieldName, model.Skip, model.PageSize);

            return View(model);
        }

        public async Task<IActionResult> Details(string? id)
        {
            if (id == null || this._userRepository == null)
            {
                return NotFound();
            }

            try
            {
                var model = new AdminPanelDetailsViewModel
                {
                    User = await this._userRepository.GetByIdAsync(id),
                    Roles = await this._userRepository.GetRolesAsync(id),
                };

                return View(model);
            }
            catch (NullReferenceException ex)
            {
                return NotFound(ex.Message);
            }
        }

        public async Task<IActionResult> Create(string? id)
        {
            if (id == null)
            {
                ViewData["Action"] = "Create";

                var model = new AdminPanelCreateViewModel
                {
                    User = new IdentityUser(),
                    Roles = await this._userRepository.GetAllRolesAsync(),
                    Password = "",
                    Email = "",
                    PhoneNumber = ""
                };

                return View(model);
            }

            ViewData["Action"] = "Edit";
            try
            {
                var model = new AdminPanelCreateViewModel
                {
                    User = await this._userRepository.GetByIdAsync(id),
                    Roles = await this._userRepository.GetAllRolesAsync(),
                    Password = ""
                };

                model.PhoneNumber = model.User.PhoneNumber;
                model.Email = model.User.Email;

                return View(model);
            }
            catch (NullReferenceException ex)
            {
                return NotFound(ex.Message);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(string? id, AdminPanelCreateViewModel model)
        {
            if (!ModelState.IsValid || model.User == null)
            {
                return View(model);
            }

            model.User.PhoneNumber = model.PhoneNumber;
            model.User.Email = model.Email;

            try
            {
                if (await this._userRepository.GetByIdAsync(id) != null)
                {
                    await this._userRepository.UpdateAsync(model.User, model.Roles);
                }
                else
                {
                    await this._userRepository.AddAsync(model.User, model.Password, model.Roles);
                }
            }
            catch (Exception ex)
            {
                return NotFound(ex.Message);
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (this._userRepository == null)
            {
                return Problem("Repository class implementing 'IIdentityUserRepository' is null.");
            }

            var user = await this._userRepository.GetByIdAsync(id);

            if (user != null)
            {
                await this._userRepository.DeleteAsync(user.Id);
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

CdDiskStoreAspNetCore/Controllers/DebtorsController.cs
using CdDiskStoreAspNetCore.Data.Repository;
using CdDiskStoreAspNetCore.Models;
using CdDiskStoreAspNetCore.Models.Enums;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CdDiskStoreAspNetCore.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class DebtorsController : Controller
    {
        private readonly IDebtorsRepository _debtorsRepository;

        public DebtorsController(IDebtorsRepository debtorsRepository)
        {
            this._debtorsRepository = debtorsRepository;
        }

        public async Task<IActionResult> Index(string? filter, MySortOrder sortOrder, string? filterFieldName, string? sortField = "Id", int skip = 0)
        {
            var model = new IndexViewModel<Debtor>
            {
                Filter = filter,
                FilterFieldName = filterFieldName ?? IndexViewModel<Debtor>.FilterableFieldNames[0],
                SortFieldName = sortField,
                SortOrder = sortOrder,
                Skip = skip,
                PageSize = 20,
                CountItems = await this._debtorsRepository.GetProcessedDataCountAsync(filter, filterFieldName)
            };

            model.Items = await this._debtorsRepository.GetProcessedDataAsync(model.Filter, model.FilterFieldName, model.SortOrder, model.SortFieldName, model.Skip, model.PageSize);

            return View(model);
        }
    }
}

CdDiskStoreAspNetCore/Controllers/QuarterIncomesController.cs
using CdDiskStoreAspNetCore.Data.Repository;
using CdDiskStoreAspNetCore.Models.Enums;
using CdDiskStoreAspNetCore.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CdDiskStoreAspNetCore.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class QuarterIncomesController : Controller
    {
        private readonly IQuarterIncomeRepository _quarterIncomeRepository;

        public QuarterIncomesController(IQuarterIncomeRepository quarterIncomeRepository)
        {
            this._quarterIncomeRepository = quarterIncomeRepository;
        }

        public async Task<IActionResult> Index(MySortOrder sortOrder, string? sortField = "Id", int skip = 0)
        {
            var model = new IndexViewModel<QuarterIncome>
            {
                SortFieldName = sortField,
                SortOrder = sortOrder,
                Skip = skip,
                PageSize = 20,
                CountItems = await this._quarterIncomeRepository.CountAsync()
            };

            model.Items = await this._quarterIncomeRepository.GetProcessedDataAsync(model.SortOrder, model.SortFieldName, model.Skip, model.PageSize);

            return View(model);
        }
    }
}

CdDiskStoreAspNetCore/Controllers/UselessDiscsController.cs
using CdDiskStoreAspNetCore.Data.Repository;
using CdDiskStoreAspNetCore.Models.Enums;
using CdDiskStoreAspNetCore.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;

namespace CdDiskStoreAspNetCore.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class UselessDiscsController : Controller
    {
        private readonly IUselessDiscsRepository _uselessDiscsRepository;

        public UselessDiscsController(IUselessDiscsRepository uselessDiscsRepository)
        {
            this._uselessDiscsRepository = uselessDiscsRepository;
        }

        public async Task<IActionResult> Index(string? filter, MySortOrder sortOrder, string? filterFieldName, string? sortField = "Id", int skip = 0)
        {
            var model = new IndexViewModel<UselessDisc>
            {
                Filter = filter,
                FilterFieldName = filterFieldName ?? IndexViewModel<UselessDisc>.FilterableFieldNames[0],
                SortFieldName = sortField,
                SortOrder = sortOrder,
                Skip = skip,
                CountItems = await this._uselessDiscsRepository.GetProcessedDataCountAsync(filter, filterFieldName)
            };

            model.Items = await this._uselessDiscsRepository.GetProcessedDataAsync(model.Filter, model.FilterFieldName, model.SortOrder, model.SortFieldName, model.Skip, model.PageSize);

            return View(model);
        }
    }
}

CdDiskStoreAspNetCore/Views/AdminPanel/Create.cshtml
@using Microsoft.AspNetCore.Identity
@model AdminPanelCreateViewModel

@{
    string action = ViewData["Action"] as string;
}

<div class="container mt-3">
    <h1>@action</h1>

    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Website User</h4>
            <hr />
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="User.Id" />

                <div class="form-group">
                    <label asp-for="User.UserName" class="control-label"></label>
                    <input asp-for="User.UserName" class="form-control" />
                    <span asp-validation-for="User.UserName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Email" class="control-label"></label>
                    <input placeholder="user@example.com" asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PhoneNumber" class="control-label"></label>
                    <input type="tel" placeholder="0501234567" asp-for="PhoneNumber" class="form-control" />
                    <small id="phoneHelp" class="form-text text-muted">Будь ласка, введіть свій номер телефону в українському форматі (0501234567).</small>
                    <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Password" class="control-label"></label>
                    <input asp-for="Password" class="form-control" />
                    <span asp-validation-for="Password" class="text-danger"></span>
                </div>

                <div class="row form-group" title="Roles">
                    <div class="col-lg-3" title="Roles">
                        <label asp-for="Roles" class="control-label"></label>
                    </div>
                    <div class="col-lg-9">
                        <select asp-for="Roles" class="form-control" asp-items="new SelectList(Model.Roles)" multiple></select>
                    </div>
                    <span asp-validation-for="Roles" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <input type="submit" value="@action" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div class="mt-3">
        <a asp-action="Index" class="btn btn-secondary">Back to List</a>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

CdDiskStoreAspNetCore/Views/AdminPanel/Details.cshtml
@model CdDiskStoreAspNetCore.Models.AdminPanelDetailsViewModel

<div class="container mt-3">
    <h1 class="mb-4">Details</h1>

    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Website User</h4>
            <hr />

            <table class="table table-bordered table-striped">
                <tr>
                    <th class="col-sm-2">
                        @Html.DisplayNameFor(model => model.User.UserName)
                    </th>
                    <td class="col-sm-10">
                        @Html.DisplayFor(model => model.User.UserName)
                    </td>
                </tr>
                <tr>
                    <th class="col-sm-2">
                        @Html.DisplayNameFor(model => model.User.Email)
                    </th>
                    <td class="col-sm-10">
                        @Html.DisplayFor(model => model.User.Email)
                    </td>
                </tr>
                <tr>
                    <th class="col-sm-2">
                        @Html.DisplayNameFor(model => model.User.EmailConfirmed)
                    </th>
                    <td class="col-sm-10">
                        @Html.DisplayFor(model => model.User.EmailConfirmed)
                    </td>
                </tr>
                <tr>
                    <th class="col-sm-2">
                        @Html.DisplayNameFor(model => model.User.PhoneNumber)
                    </th>
                    <td class="col-sm-10">
                        @Html.DisplayFor(model => model.User.PhoneNumber)
                    </td>
                </tr>
            </table>
        </div>
    </div>

    <br />

    @if (Model.Roles != null && Model.Roles.Any())
    {
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Roles</h4>
                <hr />

                <table class="table table-responsive">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(modelItem => Model.Roles)
                            </th>
                            <th></th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach (var item in Model.Roles)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item)
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    }

    <div class="mt-3">
        <a asp-action="Create" asp-route-id="@Model?.User.Id" class="btn btn-primary">Edit</a>
        <a asp-action="Index" class="btn btn-secondary">Back to List</a>
    </div>
</div>

CdDiskStoreAspNetCore/Views/AdminPanel/Index.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManger
@model IndexViewModel<IdentityUser>

@if (!SignInManger.IsSignedIn(User) || !User.IsInRole("Administrator"))
{
    <h1 style="color: red;">ACCESS DENIED</h1>
}
else
{
    <h1>Website Users</h1>

    <div class="container">

        <div class="row mb-3">
            <div class="col-md-3">

                <div class="card">
                    <div class="card-body">
                        <h4>Views</h4>
                        <div class="d-flex flex-column">
                            <form method="post" asp-controller="Debtors" asp-action="Index">
                                <input type="submit" class="btn btn-primary mb-2 w-100" value="Debtors" />
                            </form>

                            <form method="post" asp-controller="QuarterIncomes" asp-action="Index">
                                <input type="submit" class="btn btn-primary mb-2 w-100" value="Income Per Each Financial Quarter" />
                            </form>

                            <form method="post" asp-controller="ProfitFromClients" asp-action="Index">
                                <input type="submit" class="btn btn-primary mb-2 w-100" value="Profit From Each Client" />
                            </form>

                            <form method="post" asp-controller="UselessDiscs" asp-action="Index">
                                <input type="submit" class="btn btn-primary mb-2 w-100" value="Useless Discs" />
                            </form>

                            <form method="post" asp-controller="AdultFilmRatios" asp-action="Index">
                                <input type="submit" class="btn btn-primary mb-2 w-100" value="18+ Film Ratio By Month" />
                            </form>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-9">
                <div class="container">
                    <div class="row mb-3">
                        <div class="col-md-3">
                            <h3>Create new user</h3>
                        </div>
                        <div class="col-md-1">
                            <a asp-action="Create">
                                <i class="icon-button add-button fas fa-plus"></i>
                            </a>
                        </div>
                    </div>

                    <form asp-controller="AdminPanel" asp-action="Index" method="post">
                        <div class="row mb-3">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label asp-for="FilterFieldName">Filter by:</label>
                                    @Html.DropDownList("FilterFieldName", new SelectList(new List<string> { "UserName", "Email", "PhoneNumber" }, Model.FilterFieldName), new { @class = "form-control" })
                                </div>
                            </div>

                            <div class="col-md-5">
                                <div class="form-group">
                                    <label for="filter">Filter:</label>
                                    <input type="text" id="filter" name="filter" value="@Model.Filter" class="form-control" />
                                </div>
                            </div>

                            <div class="col-md-3 d-grid">
                                <input type="submit" value="Filter" class="btn btn-primary" title="Filter" />
                            </div>
                        </div>
                    </form>
                </div>

                <div class="row" style="width: 80vw;">
                    @if (Model.Items != null && Model.Items.Any())
                    {
                        <table class="table table-responsive">
                            <thead>
                                <tr>
                                    <th>
                                        @{
                                            await Html.RenderPartialAsync("_SortField", new SortModel { ViewModel = Model, FieldName = "UserName" });
                                        }
                                    </th>
                                    <th>
                                        @{
                                            await Html.RenderPartialAsync("_SortField", new SortModel { ViewModel = Model, FieldName = "Email" });
                                        }
                                    </th>
                                    <th>
                                        @{
                                            await Html.RenderPartialAsync("_SortField", new SortModel { ViewModel = Model, FieldName = "EmailConfirmed" });
                                        }
                                    </th>
                                    <th>
                                        @{
                                            await Html.RenderPartialAsync("_SortField", new SortModel { ViewModel = Model, FieldName = "PhoneNumber" });
                                        }
                                    </th>
                                    <th></th>
                                </tr>
                            </thead>

                            <tbody>
                                @foreach (var item in Model.Items)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.UserName)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Email)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.EmailConfirmed)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.PhoneNumber)
                                        </td>

                                        <td>
                                            <a asp-action="Create" asp-route-id="@item.Id">
                                                <i class="icon-button edit-button fas fa-edit"></i>
                                            </a>

                                            <a asp-action="Details" asp-route-id="@item.Id">
                                                <i class="icon-button details-button fas fa-eye"></i>
                                            </a>

                                            <button type="button" class="icon-button delete-button fas fa-trash-alt" data-bs-toggle="modal" data-bs-target="#exampleModal@(item.Id)"></button>

                                            <div class="modal fade" id="exampleModal@(item.Id)" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                                <div class="modal-dialog">
                                                    <div class="modal-content">
                                                        <div class="modal-header">
                                                            <h5 class="modal-title" id="exampleModalLabel">User to delete</h5>
                                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                                        </div>
                                                        <div class="modal-body">
                                                            @Html.DisplayFor(modelItem => item.Email)
                                                        </div>
                                                        <div class="modal-footer">
                                                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                                            <form method="post" asp-action="Delete" asp-route-id="@item.Id">
                                                                <input type="hidden" asp-for="@item.Id" />
                                                                <input type="submit" value="Delete" class="btn btn-danger" />
                                                            </form>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    }
                    else
                    {
                        <h1>No users in the database</h1>
                    }

                    @{
                        await Html.RenderPartialAsync("_Pagination", Model);
                    }
                </div>
            </div>
        </div>
    </div>
}
<style>
    .container {
        margin-left: 0px;
    }
</style>