CdDiskStoreAspNetCore/Controllers/AdminPanelController.cs
using CdDiskStoreAspNetCore.Data.Repository;
using CdDiskStoreAspNetCore.Models;
using CdDiskStoreAspNetCore.Models.Enums;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace CdDiskStoreAspNetCore.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class AdminPanelController : Controller
    {
        private readonly IIdentityUserRepository _userRepository;

        public AdminPanelController(IIdentityUserRepository userRepository)
        {
            this._userRepository = userRepository;
        }

        public async Task<IActionResult> Index(string? filter, MySortOrder sortOrder, string? filterFieldName, string? sortField = "Id", int skip = 0)
        {
            var model = new IndexViewModel<IdentityUser>
            {
                Filter = filter,
                FilterFieldName = filterFieldName ?? IndexViewModel<IdentityUser>.FilterableFieldNames[0],
                SortFieldName = sortField,
                SortOrder = sortOrder,
                Skip = skip,
                CountItems = await this._userRepository.GetProcessedDataCountAsync(filter, filterFieldName)
            };

            model.Items = await this._userRepository.GetProcessedDataAsync(model.Filter, model.FilterFieldName, model.SortOrder, model.SortFieldName, model.Skip, model.PageSize);

            return View(model);
        }

        public async Task<IActionResult> Details(string? id)
        {
            if (id == null || this._userRepository == null)
            {
                return NotFound();
            }

            try
            {
                var model = new AdminPanelDetailsViewModel
                {
                    User = await this._userRepository.GetByIdAsync(id),
                    Roles = await this._userRepository.GetRolesAsync(id),
                };

                return View(model);
            }
            catch (NullReferenceException ex)
            {
                return NotFound(ex.Message);
            }
        }

        public async Task<IActionResult> Create(string? id)
        {
            if (id == null)
            {
                ViewData["Action"] = "Create";

                var model = new AdminPanelCreateViewModel
                {
                    User = new IdentityUser(),
                    Roles = await this._userRepository.GetAllRolesAsync(),
                    Password = "",
                    Email = "",
                    PhoneNumber = ""
                };

                return View(model);
            }

            ViewData["Action"] = "Edit";
            try
            {
                var model = new AdminPanelCreateViewModel
                {
                    User = await this._userRepository.GetByIdAsync(id),
                    Roles = await this._userRepository.GetAllRolesAsync(),
                    Password = ""
                };

                model.PhoneNumber = model.User.PhoneNumber;
                model.Email = model.User.Email;

                return View(model);
            }
            catch (NullReferenceException ex)
            {
                return NotFound(ex.Message);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(string? id, AdminPanelCreateViewModel model)
        {
            if (!ModelState.IsValid || model.User == null)
            {
                return View(model);
            }

            model.User.PhoneNumber = model.PhoneNumber;
            model.User.Email = model.Email;

            try
            {
                if (await this._userRepository.GetByIdAsync(id) != null)
                {
                    await this._userRepository.UpdateAsync(model.User, model.Roles);
                }
                else
                {
                    await this._userRepository.AddAsync(model.User, model.Password, model.Roles);
                }
            }
            catch (Exception ex)
            {
                return NotFound(ex.Message);
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (this._userRepository == null)
            {
                return Problem("Repository class implementing 'IIdentityUserRepository' is null.");
            }

            var user = await this._userRepository.GetByIdAsync(id);

            if (user != null)
            {
                await this._userRepository.DeleteAsync(user.Id);
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

CdDiskStoreAspNetCore/Controllers/ProfitFromClientsController.cs
using CdDiskStoreAspNetCore.Data.Repository;
using CdDiskStoreAspNetCore.Models;
using CdDiskStoreAspNetCore.Models.Enums;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CdDiskStoreAspNetCore.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class ProfitFromClientsController : Controller
    {
        private readonly IProfitFromClientRepository _profitFromClientRepository;

        public ProfitFromClientsController(IProfitFromClientRepository profitFromClientRepository)
        {
            this._profitFromClientRepository = profitFromClientRepository;
        }

        public async Task<IActionResult> Index(string? filter, MySortOrder sortOrder, string? filterFieldName, string? sortField = "ClientId", int skip = 0)
        {
            var model = new IndexViewModel<ProfitFromClient>
            {
                Filter = filter,
                FilterFieldName = filterFieldName ?? IndexViewModel<ProfitFromClient>.FilterableFieldNames[0],
                SortFieldName = sortField,
                SortOrder = sortOrder,
                Skip = skip,
                PageSize = 20,
                CountItems = await this._profitFromClientRepository.GetProcessedDataCountAsync(filter, filterFieldName)
            };

            model.Items = await this._profitFromClientRepository.GetProcessedDataAsync(model.Filter, model.FilterFieldName, model.SortOrder, model.SortFieldName, model.Skip, model.PageSize);

            return View(model);
        }
    }
}

CdDiskStoreAspNetCore/Views/ProfitFromClients/Index.cshtml
@using Microsoft.AspNetCore.Identity
@using CdDiskStoreAspNetCore.Data.Repository;
@model IndexViewModel<ProfitFromClient>
@inject SignInManager<IdentityUser> SignInManger

@if (!SignInManger.IsSignedIn(User) || !User.IsInRole("Administrator"))
{
    <h1 style="color: red;">ACCESS DENIED</h1>
}
else
{
    <h1>Debtors</h1>

    <div class="container">
        <div class="container">
            <form asp-controller="ProfitFromClients" asp-action="Index" method="post">
                <div class="row mb-3">
                    <div class="col-md-4">
                        <div class="form-group">
                            <label asp-for="FilterFieldName">Filter by:</label>
                            @Html.DropDownList("FilterFieldName", new SelectList(IndexViewModel<Debtor>.FilterableFieldNames, Model.FilterFieldName), new { @class = "form-control" })
                        </div>
                    </div>

                    <div class="col-md-5">
                        <div class="form-group">
                            <label for="filter">Filter:</label>
                            <input type="text" id="filter" name="filter" value="@Model.Filter" class="form-control" />
                        </div>
                    </div>

                    <div class="col-md-3 d-grid">
                        <input type="submit" value="Filter" class="btn btn-primary" title="Filter" />
                    </div>
                </div>
            </form>
        </div>

        <div class="row" style="width: 80vw;">
            @if (Model.Items != null && Model.Items.Any())
            {
                <table class="table table-responsive">
                    <thead>
                        <tr>
                            <th>
                                @{
                                    await Html.RenderPartialAsync("_SortField", new SortModel { ViewModel = Model, FieldName = "ClientName" });
                                }
                            </th>
                            <th>
                                @{
                                    await Html.RenderPartialAsync("_SortField", new SortModel { ViewModel = Model, FieldName = "OrderYear" });
                                }
                            </th>
                            <th>
                                @{
                                    await Html.RenderPartialAsync("_SortField", new SortModel { ViewModel = Model, FieldName = "MusicPurchase" });
                                }
                            </th>
                            <th>
                                @{
                                    await Html.RenderPartialAsync("_SortField", new SortModel { ViewModel = Model, FieldName = "MusicRent" });
                                }
                            </th>
                            <th>
                                @{
                                    await Html.RenderPartialAsync("_SortField", new SortModel { ViewModel = Model, FieldName = "FilmPurchase" });
                                }
                            </th>
                            <th>
                                @{
                                    await Html.RenderPartialAsync("_SortField", new SortModel { ViewModel = Model, FieldName = "FilmRent" });
                                }
                            </th>
                            <th></th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach (var item in Model.Items)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ClientName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.OrderYear)
                                </td>
                                <td>
                                    @string.Format("{0:C2}", item.MusicPurchase)
                                </td>
                                <td>
                                    @string.Format("{0:C2}", item.MusicRent)
                                </td>
                                <td>
                                    @string.Format("{0:C2}", item.FilmPurchase)
                                </td>
                                <td>
                                    @string.Format("{0:C2}", item.FilmRent)
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            }
            else
            {
                <h1>No data in the database</h1>
            }

            @{
                await Html.RenderPartialAsync("_Pagination", Model);
            }
        </div>

        <div class="mt-3">
            <a asp-controller="AdminPanel" asp-action="Index" class="btn btn-secondary">Back to Admin Panel</a>
        </div>
    </div>
}